"""Shared scaffolding for the Unicode table generators (gen_unicode_props.py, gen_unicode_fold.py).

The two generators build different data (property ranges vs case-fold orbits) from different oracles,
but they share the same envelope: a GENERATED file header with the pinned Unicode version, an
exhaustive validation pass that aborts on any disagreement with `re`, and the write-and-report tail.
That envelope lives here so each generator stays just its algorithm plus configuration; the emitted
bytes are unchanged (the regen guards assert byte-identity).
"""
import sys
import unicodedata


def unidata_version():
    """The running CPython's Unicode data version -- the pin baked into each generated header."""
    return unicodedata.unidata_version


def file_header(*, filename, brief, generator, doc_lines, guard, includes, version_kind, version_const):
    """The GENERATED-header preamble shared by both tables, up to and including the version constant.

    Parameters carry every part that differs between the two headers so the output is byte-for-byte
    what each generator emitted before this module existed.

    Args:
        filename: The header's basename (for the \\file line).
        brief: The \\brief one-liner.
        generator: The producing script's basename (for the DO-NOT-EDIT line).
        doc_lines: Body doc lines (already Unicode-version-interpolated), each emitted as ` * <line>`.
        guard: The include-guard macro.
        includes: Exact `#include` lines (and any interleaved blank) between version.hpp and namespace.
        version_kind: The noun in the version-constant doc ("tables" or "orbits").
        version_const: The name of the emitted `..._unidata_version` constant.
    """
    ver = unidata_version()
    out = [
        "/*!",
        f" * \\file {filename}",
        f" * \\brief {brief}",
        " *",
        f" * GENERATED by tools/{generator} -- DO NOT EDIT BY HAND.",
        " *",
    ]
    out += [f" * {line}" for line in doc_lines]
    out += [
        " */",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "// Internal — do not include directly.",
        "// Users: #include <real/real.hpp> (or the documented opt-ins <real/dfa.hpp>, <real/std/regex.hpp>).",
        "",
        '#include "real/version.hpp"',
        "",
    ]
    out += includes
    out += [
        "",
        "namespace real::detail {",
        "",
        f"  //! \\brief The Unicode data version these {version_kind} were generated from ({ver}).",
        f'  inline constexpr const char* {version_const} {{"{ver}"}};',
        "",
    ]
    return out


def file_footer(guard):
    """The namespace-close + include-guard-close tail shared by both headers."""
    return [
        "} // namespace real::detail",
        "",
        f"#endif // {guard}",
        "",
    ]


def validate_exhaustive(code_points, check, on_abort):
    """Second-net validation: every code point's built-table answer must agree with `re`.

    Loops `code_points`, and for each calls `check(cp)`; a non-None return is a disagreement whose
    string is printed (up to eight). If any disagreed, aborts (sys.exit) with `on_abort(count)` -- so a
    table-building bug can never slip past into a committed header. Each generator supplies its own
    `check`/`on_abort` so the diagnostic wording stays exactly what it was (ranges vs orbits).

    Args:
        code_points: Iterable of code points to check.
        check: cp -> None if the table agrees with `re`, else a short mismatch-detail string.
        on_abort: count -> the sys.exit message when any code point disagreed.
    """
    mismatches = 0
    for cp in code_points:
        detail = check(cp)
        if detail is not None:
            mismatches += 1
            if mismatches <= 8:
                print("  MISMATCH " + detail, file=sys.stderr)
    if mismatches:
        sys.exit(on_abort(mismatches))


def write_lines(path, lines, summary):
    """Write `lines` (newline-joined, trailing newline) to `path` and print `summary`."""
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(summary)
